const MOCK={totalQuestions:47,totalMarks:100,durationSeconds:195*60};let test=[],answers={},reviewed=new Set(),current=0,timeLeft=MOCK.durationSeconds,timerId;
const $=id=>document.getElementById(id);
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function buildTest(){const groups=await Promise.all(['firstFlight','footprints','grammar','rtc','composition','comprehension'].map(async type=>{try{return(await QuestionBankLoader.loadBank(type)).map(x=>({...x,_source:type}))}catch{return[]}}));const all=groups.flat();test=shuffle(all).slice(0,MOCK.totalQuestions);if(test.length<MOCK.totalQuestions){throw Error(`Only ${test.length} validated questions are available; 47 are required.`)}renderPalette();renderQuestion();startTimer()}
function renderPalette(){const p=$('palette');p.innerHTML='';test.forEach((_,i)=>{const b=document.createElement('button');b.textContent=i+1;b.type='button';b.addEventListener('click',()=>{current=i;renderQuestion()});p.appendChild(b)})}
function renderQuestion(){const x=test[current];$('counter').textContent=`Question ${current+1} of ${test.length}`;$('section').textContent=x._source==='firstFlight'?'First Flight':x._source==='footprints'?'Footprints Without Feet':x._source.toUpperCase();$('feedback').textContent=reviewed.has(current)?'Marked for review.':'';const q=x.prompt||x.text||x.question||'Read and answer.';$('question').innerHTML=`<h2>${current+1}. ${esc(q)}</h2>`;const box=$('answer');box.innerHTML='';if(x.type==='unseen_passage'){const p=document.createElement('p');p.className='passage';p.textContent=x.passage||'';box.appendChild(p);(x.questions||[]).forEach((z,i)=>{const label=document.createElement('label');label.innerHTML=`<p><strong>${i+1}. ${esc(z.q)}</strong></p><textarea rows="3" data-sub="${i}"></textarea>`;box.appendChild(label)})}else if(Array.isArray(x.options)){x.options.forEach((o,i)=>{const l=document.createElement('label');l.className='option';l.innerHTML=`<input type="radio" name="mock-answer" value="${i}"><span>${esc(o)}</span>`;box.appendChild(l)});}else{const t=document.createElement('textarea');t.rows=x.type==='essay'||x.type==='letter'?14:6;t.placeholder='Write your answer here…';box.appendChild(t)}restoreAnswer();}
function capture(){const x=test[current];if(Array.isArray(x.options)){const s=document.querySelector('input[name="mock-answer"]:checked');answers[current]=s?s.value:''}else if(x.type==='unseen_passage'){answers[current]=[...document.querySelectorAll('[data-sub]')].map(t=>t.value)}else{const t=$('answer').querySelector('textarea');answers[current]=t?t.value:''}}
function restoreAnswer(){const a=answers[current];if(a===undefined)return;const x=test[current];if(Array.isArray(x.options)){const r=document.querySelector(`input[name="mock-answer"][value="${CSS.escape(String(a))}"]`);if(r)r.checked=true}else if(x.type==='unseen_passage'&&Array.isArray(a)){document.querySelectorAll('[data-sub]').forEach((t,i)=>t.value=a[i]||'')}else{const t=$('answer').querySelector('textarea');if(t)t.value=a||''}}
function startTimer(){timerId=setInterval(()=>{timeLeft--;updateTimer();if(timeLeft<=0){clearInterval(timerId);submitTest(true)}},1000);updateTimer()}
function updateTimer(){const m=Math.floor(timeLeft/60),s=timeLeft%60;$('timer').textContent=`${m}:${String(s).padStart(2,'0')}`;$('timer').classList.toggle('warning',timeLeft<=300)}
function submitTest(auto=false){capture();clearInterval(timerId);const objective=test.reduce((n,x,i)=>n+(Array.isArray(x.options)&&String(answers[i])===String(x.answer)?1:0),0);sessionStorage.setItem('eh15e.mock.result',JSON.stringify({totalQuestions:test.length,totalMarks:MOCK.totalMarks,objectiveCorrect:objective,answers,reviewed:[...reviewed],autoSubmitted:auto,completedAt:new Date().toISOString()}));$('question').innerHTML='<div class="result-box"><h2>Test submitted</h2><p>Objective score: '+objective+' correct.</p><p>Written responses have been saved for review. The final 15-E result should only be calculated after the applicable written-answer marking rules are applied.</p></div>';$('answer').innerHTML='';$('feedback').textContent=auto?'Time expired; the test was submitted automatically.':'Your test has been submitted.';document.querySelectorAll('.mock-actions button').forEach(b=>b.disabled=true)}
$('prev').onclick=()=>{capture();if(current>0){current--;renderQuestion()}};$('next').onclick=()=>{capture();if(current<test.length-1){current++;renderQuestion()}};$('review').onclick=()=>{reviewed.has(current)?reviewed.delete(current):reviewed.add(current);renderQuestion()};$('submit').onclick=()=>{capture();if(confirm('Submit the full mock test now?'))submitTest(false)};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}buildTest().catch(e=>{$('question').textContent=e.message;$('feedback').textContent='The mock test was not started because the required 47-question validated pool is not yet available.';});